name: maile_app_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  flutter: 
      sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  # bruno ui
  bruno: 3.0.0
  # 后台保活
  # workmanager: ^0.5.0
  # 微信SDK
  # fluwx: ^3.9.2
  # H5插件
  webview_flutter: ^3.0.4
  # H5 交互
  ds_bridge_webview: ^0.0.1
  # 宫格
  flutter_staggered_grid_view: ^0.6.2
  # 网络图片缓存
  # cached_network_image: ^3.2.2
  # 底部导航
  persistent_bottom_nav_bar_v2: ^4.2.5
  # 类似抽屉
  backdrop: ^0.8.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/car_new.png
    - assets/icons/descend.png
    - assets/icons/wholesale.png
  fonts:
    - family: DIN_Alternate
      fonts:
        - asset: assets/fonts/DIN_Alternate_Bold.ttf
          weight: 800



